replicaCount: 1
image:
  repository: dimozone/attestation-api
  pullPolicy: IfNotPresent
  tag: f9efba3
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
cronJob:
  enabled: false
  schedule: 0 0 * * 0
env:
  PORT: 8080
  MON_PORT: 8888
  GRPC_PORT: 8086
  ENABLE_PPROF: false
  DEFINITIONS_GRPC_ADDR: device-definitions-api-dev:8086
  TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://dex-roles-rights.dev.svc.cluster.local:5556/keys
  TOKEN_EXCHANGE_ISSUER_URL: https://auth-roles-rights.dev.dimo.zone
  VEHICLE_NFT_ADDRESS: '0x45fbCD3ef7361d156e8b16F5538AE36DEdf61Da8'
  AFTERMARKET_NFT_ADDRESS: '0x325b45949C833986bC98e98a49F3CA5C5c4643B5'
  SYNTHETIC_NFT_ADDRESS: '0x78513c8CB4D6B6079f813850376bc9c7fc8aE67f'
  TELEMETRY_URL: https://telemetry-api.dev.dimo.zone
  IDENTITY_API_URL: http://identity-api-dev:8080
  DIS_URL: https://attest.dev.dimo.zone
  DEX_URL: https://auth.dev.dimo.zone
  DEV_LICENSE: '0x52fD9Dc294066792785CcD85eFB9A0Bd48DE01E4'
  FETCH_GRPC_ADDR: fetch-api-dev:8086
  DIMO_REGISTRY_CHAIN_ID: 80002
  DEV_LICENSE_REDIRECT_URL: http://127.0.0.1:10000
  VIN_DATA_VERSION: vin/v1.0
  POMVC_DATA_TYPE: POMVCv1.0
  CLOUDEVENT_BUCKET: dimo-ingest-cloudevent-dev
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
    grpc:
      port: 8086
      targetPort: grpc
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: grpc
    containerPort: 8086
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dev.dimo.zone, https://admin.dev.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '25'
    external-dns.alpha.kubernetes.io/hostname: attestation-api.dev.dimo.zone
  hosts:
    - host: attestation-api.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics: []
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
