replicaCount: 2
image:
  repository: dimozone/attestation-api
  pullPolicy: IfNotPresent
  tag: 0.0.21
cronJob:
  enabled: false
  schedule: 0 0 * * 0
env:
  PORT: 8080
  MON_PORT: 8888
  TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://dex-roles-rights-prod.prod.svc.cluster.local:5556/keys
  TOKEN_EXCHANGE_ISSUER_URL: https://auth-roles-rights.dimo.zone
  VEHICLE_NFT_ADDRESS: '0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF'
  AFTERMARKET_NFT_ADDRESS: '0x9c94C395cBcBDe662235E0A9d3bB87Ad708561BA'
  SYNTHETIC_NFT_ADDRESS: '0x4804e8D1661cd1a1e5dDdE1ff458A7f878c0aC6D'
  DEFINITIONS_GRPC_ADDR: device-definitions-api-prod:8086
  TELEMETRY_URL: https://telemetry-api.dimo.zone
  IDENTITY_API_URL: http://identity-api-prod:8080
  FINGERPRINT_BUCKET: dimo-network-fingerprint-prod
  AUTOPI_BUCKET_NAME: dimo-network-connectivity-prod
  HASHDOG_BUCKET_NAME: dimo-network-connectivity-prod
  STATUS_BUCKET_NAME: dimo-network-status-prod
  VC_BUCKET: dimo-ingest-cloudevent-prod
  CLOUDEVENT_BUCKET: dimo-ingest-cloudevent-prod
  DIMO_REGISTRY_CHAIN_ID: 137
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone, https://admin.team.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '50'
    external-dns.alpha.kubernetes.io/hostname: attestation-api.dimo.zone
  hosts:
    - host: attestation-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
