apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "attestation-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/attestation/dinc-storage-node/signer-private-key
    secretKey: SIGNER_PRIVATE_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "attestation-api.fullname" . }}-secret
    template:
      metadata: {}
