// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=pom_test
//

// Package pom_test is a generated GoMock package.
package pom_test

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	models "github.com/DIMO-Network/attestation-api/internal/models"
	verifiable "github.com/DIMO-Network/attestation-api/pkg/verifiable"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockVCRepo is a mock of VCRepo interface.
type MockVCRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVCRepoMockRecorder
	isgomock struct{}
}

// MockVCRepoMockRecorder is the mock recorder for MockVCRepo.
type MockVCRepoMockRecorder struct {
	mock *MockVCRepo
}

// NewMockVCRepo creates a new mock instance.
func NewMockVCRepo(ctrl *gomock.Controller) *MockVCRepo {
	mock := &MockVCRepo{ctrl: ctrl}
	mock.recorder = &MockVCRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVCRepo) EXPECT() *MockVCRepoMockRecorder {
	return m.recorder
}

// StorePOMVC mocks base method.
func (m *MockVCRepo) StorePOMVC(ctx context.Context, tokenID uint32, vinvc json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePOMVC", ctx, tokenID, vinvc)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePOMVC indicates an expected call of StorePOMVC.
func (mr *MockVCRepoMockRecorder) StorePOMVC(ctx, tokenID, vinvc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePOMVC", reflect.TypeOf((*MockVCRepo)(nil).StorePOMVC), ctx, tokenID, vinvc)
}

// MockIdentityAPI is a mock of IdentityAPI interface.
type MockIdentityAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityAPIMockRecorder
	isgomock struct{}
}

// MockIdentityAPIMockRecorder is the mock recorder for MockIdentityAPI.
type MockIdentityAPIMockRecorder struct {
	mock *MockIdentityAPI
}

// NewMockIdentityAPI creates a new mock instance.
func NewMockIdentityAPI(ctrl *gomock.Controller) *MockIdentityAPI {
	mock := &MockIdentityAPI{ctrl: ctrl}
	mock.recorder = &MockIdentityAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityAPI) EXPECT() *MockIdentityAPIMockRecorder {
	return m.recorder
}

// GetVehicleInfo mocks base method.
func (m *MockIdentityAPI) GetVehicleInfo(ctx context.Context, tokenID uint32) (*models.VehicleInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleInfo", ctx, tokenID)
	ret0, _ := ret[0].(*models.VehicleInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleInfo indicates an expected call of GetVehicleInfo.
func (mr *MockIdentityAPIMockRecorder) GetVehicleInfo(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleInfo", reflect.TypeOf((*MockIdentityAPI)(nil).GetVehicleInfo), ctx, tokenID)
}

// MockConnectivityRepo is a mock of ConnectivityRepo interface.
type MockConnectivityRepo struct {
	ctrl     *gomock.Controller
	recorder *MockConnectivityRepoMockRecorder
	isgomock struct{}
}

// MockConnectivityRepoMockRecorder is the mock recorder for MockConnectivityRepo.
type MockConnectivityRepoMockRecorder struct {
	mock *MockConnectivityRepo
}

// NewMockConnectivityRepo creates a new mock instance.
func NewMockConnectivityRepo(ctrl *gomock.Controller) *MockConnectivityRepo {
	mock := &MockConnectivityRepo{ctrl: ctrl}
	mock.recorder = &MockConnectivityRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectivityRepo) EXPECT() *MockConnectivityRepoMockRecorder {
	return m.recorder
}

// GetAutoPiEvents mocks base method.
func (m *MockConnectivityRepo) GetAutoPiEvents(ctx context.Context, pairedDeviceIMEI string, after, before time.Time, limit int) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoPiEvents", ctx, pairedDeviceIMEI, after, before, limit)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoPiEvents indicates an expected call of GetAutoPiEvents.
func (mr *MockConnectivityRepoMockRecorder) GetAutoPiEvents(ctx, pairedDeviceIMEI, after, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoPiEvents", reflect.TypeOf((*MockConnectivityRepo)(nil).GetAutoPiEvents), ctx, pairedDeviceIMEI, after, before, limit)
}

// GetHashDogEvents mocks base method.
func (m *MockConnectivityRepo) GetHashDogEvents(ctx context.Context, pairedDeviceAddr common.Address, after, before time.Time, limit int) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHashDogEvents", ctx, pairedDeviceAddr, after, before, limit)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHashDogEvents indicates an expected call of GetHashDogEvents.
func (mr *MockConnectivityRepoMockRecorder) GetHashDogEvents(ctx, pairedDeviceAddr, after, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHashDogEvents", reflect.TypeOf((*MockConnectivityRepo)(nil).GetHashDogEvents), ctx, pairedDeviceAddr, after, before, limit)
}

// GetStatusEvents mocks base method.
func (m *MockConnectivityRepo) GetStatusEvents(ctx context.Context, vehicleTokenID uint32, after, before time.Time, limit int) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusEvents", ctx, vehicleTokenID, after, before, limit)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusEvents indicates an expected call of GetStatusEvents.
func (mr *MockConnectivityRepoMockRecorder) GetStatusEvents(ctx, vehicleTokenID, after, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusEvents", reflect.TypeOf((*MockConnectivityRepo)(nil).GetStatusEvents), ctx, vehicleTokenID, after, before, limit)
}

// MockIssuer is a mock of Issuer interface.
type MockIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockIssuerMockRecorder
	isgomock struct{}
}

// MockIssuerMockRecorder is the mock recorder for MockIssuer.
type MockIssuerMockRecorder struct {
	mock *MockIssuer
}

// NewMockIssuer creates a new mock instance.
func NewMockIssuer(ctrl *gomock.Controller) *MockIssuer {
	mock := &MockIssuer{ctrl: ctrl}
	mock.recorder = &MockIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssuer) EXPECT() *MockIssuerMockRecorder {
	return m.recorder
}

// CreatePOMVC mocks base method.
func (m *MockIssuer) CreatePOMVC(vinSubject verifiable.POMSubject) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePOMVC", vinSubject)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePOMVC indicates an expected call of CreatePOMVC.
func (mr *MockIssuerMockRecorder) CreatePOMVC(vinSubject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePOMVC", reflect.TypeOf((*MockIssuer)(nil).CreatePOMVC), vinSubject)
}
