// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: pkg/grpc/atttestation-api.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureVinVcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token Id of the VC to ensure.
	TokenId uint32 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// If true, the VC will be created even if it already exists.
	Force bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	// The recorded at time of the VIN VC must be before this time.
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureVinVcRequest) Reset() {
	*x = EnsureVinVcRequest{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureVinVcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVinVcRequest) ProtoMessage() {}

func (x *EnsureVinVcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVinVcRequest.ProtoReflect.Descriptor instead.
func (*EnsureVinVcRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureVinVcRequest) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *EnsureVinVcRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *EnsureVinVcRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type EnsureVinVcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawVc         string                 `protobuf:"bytes,1,opt,name=raw_vc,json=rawVc,proto3" json:"raw_vc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureVinVcResponse) Reset() {
	*x = EnsureVinVcResponse{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureVinVcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVinVcResponse) ProtoMessage() {}

func (x *EnsureVinVcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVinVcResponse.ProtoReflect.Descriptor instead.
func (*EnsureVinVcResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureVinVcResponse) GetRawVc() string {
	if x != nil {
		return x.RawVc
	}
	return ""
}

type GetLatestVinVcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       uint32                 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVinVcRequest) Reset() {
	*x = GetLatestVinVcRequest{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVinVcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVinVcRequest) ProtoMessage() {}

func (x *GetLatestVinVcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVinVcRequest.ProtoReflect.Descriptor instead.
func (*GetLatestVinVcRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestVinVcRequest) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type GetLatestVinVcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawVc         string                 `protobuf:"bytes,1,opt,name=raw_vc,json=rawVc,proto3" json:"raw_vc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVinVcResponse) Reset() {
	*x = GetLatestVinVcResponse{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVinVcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVinVcResponse) ProtoMessage() {}

func (x *GetLatestVinVcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVinVcResponse.ProtoReflect.Descriptor instead.
func (*GetLatestVinVcResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestVinVcResponse) GetRawVc() string {
	if x != nil {
		return x.RawVc
	}
	return ""
}

type TestVinVcCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       uint32                 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestVinVcCreationRequest) Reset() {
	*x = TestVinVcCreationRequest{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestVinVcCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestVinVcCreationRequest) ProtoMessage() {}

func (x *TestVinVcCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestVinVcCreationRequest.ProtoReflect.Descriptor instead.
func (*TestVinVcCreationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{4}
}

func (x *TestVinVcCreationRequest) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type TestVinVcCreationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawVc         string                 `protobuf:"bytes,1,opt,name=raw_vc,json=rawVc,proto3" json:"raw_vc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestVinVcCreationResponse) Reset() {
	*x = TestVinVcCreationResponse{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestVinVcCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestVinVcCreationResponse) ProtoMessage() {}

func (x *TestVinVcCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestVinVcCreationResponse.ProtoReflect.Descriptor instead.
func (*TestVinVcCreationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{5}
}

func (x *TestVinVcCreationResponse) GetRawVc() string {
	if x != nil {
		return x.RawVc
	}
	return ""
}

type ManualVinVcCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       uint32                 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualVinVcCreationRequest) Reset() {
	*x = ManualVinVcCreationRequest{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualVinVcCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualVinVcCreationRequest) ProtoMessage() {}

func (x *ManualVinVcCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualVinVcCreationRequest.ProtoReflect.Descriptor instead.
func (*ManualVinVcCreationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{6}
}

func (x *ManualVinVcCreationRequest) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *ManualVinVcCreationRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *ManualVinVcCreationRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type ManualVinVcCreationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawVc         string                 `protobuf:"bytes,1,opt,name=raw_vc,json=rawVc,proto3" json:"raw_vc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualVinVcCreationResponse) Reset() {
	*x = ManualVinVcCreationResponse{}
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualVinVcCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualVinVcCreationResponse) ProtoMessage() {}

func (x *ManualVinVcCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_atttestation_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualVinVcCreationResponse.ProtoReflect.Descriptor instead.
func (*ManualVinVcCreationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_atttestation_api_proto_rawDescGZIP(), []int{7}
}

func (x *ManualVinVcCreationResponse) GetRawVc() string {
	if x != nil {
		return x.RawVc
	}
	return ""
}

var File_pkg_grpc_atttestation_api_proto protoreflect.FileDescriptor

const file_pkg_grpc_atttestation_api_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/grpc/atttestation-api.proto\x12\x04grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\x12EnsureVinVcRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\rR\atokenId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x122\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\",\n" +
	"\x13EnsureVinVcResponse\x12\x15\n" +
	"\x06raw_vc\x18\x01 \x01(\tR\x05rawVc\"2\n" +
	"\x15GetLatestVinVcRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\rR\atokenId\"/\n" +
	"\x16GetLatestVinVcResponse\x12\x15\n" +
	"\x06raw_vc\x18\x01 \x01(\tR\x05rawVc\"5\n" +
	"\x18TestVinVcCreationRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\rR\atokenId\"2\n" +
	"\x19TestVinVcCreationResponse\x12\x15\n" +
	"\x06raw_vc\x18\x01 \x01(\tR\x05rawVc\"l\n" +
	"\x1aManualVinVcCreationRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\rR\atokenId\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\"4\n" +
	"\x1bManualVinVcCreationResponse\x12\x15\n" +
	"\x06raw_vc\x18\x01 \x01(\tR\x05rawVc2\xd7\x02\n" +
	"\x12AttestationService\x12B\n" +
	"\vEnsureVinVc\x12\x18.grpc.EnsureVinVcRequest\x1a\x19.grpc.EnsureVinVcResponse\x12K\n" +
	"\x0eGetVinVcLatest\x12\x1b.grpc.GetLatestVinVcRequest\x1a\x1c.grpc.GetLatestVinVcResponse\x12T\n" +
	"\x11TestVinVcCreation\x12\x1e.grpc.TestVinVcCreationRequest\x1a\x1f.grpc.TestVinVcCreationResponse\x12Z\n" +
	"\x13ManualVinVcCreation\x12 .grpc.ManualVinVcCreationRequest\x1a!.grpc.ManualVinVcCreationResponseB2Z0github.com/DIMO-Network/attestation-api/pkg/grpcb\x06proto3"

var (
	file_pkg_grpc_atttestation_api_proto_rawDescOnce sync.Once
	file_pkg_grpc_atttestation_api_proto_rawDescData []byte
)

func file_pkg_grpc_atttestation_api_proto_rawDescGZIP() []byte {
	file_pkg_grpc_atttestation_api_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_atttestation_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_atttestation_api_proto_rawDesc), len(file_pkg_grpc_atttestation_api_proto_rawDesc)))
	})
	return file_pkg_grpc_atttestation_api_proto_rawDescData
}

var file_pkg_grpc_atttestation_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_grpc_atttestation_api_proto_goTypes = []any{
	(*EnsureVinVcRequest)(nil),          // 0: grpc.EnsureVinVcRequest
	(*EnsureVinVcResponse)(nil),         // 1: grpc.EnsureVinVcResponse
	(*GetLatestVinVcRequest)(nil),       // 2: grpc.GetLatestVinVcRequest
	(*GetLatestVinVcResponse)(nil),      // 3: grpc.GetLatestVinVcResponse
	(*TestVinVcCreationRequest)(nil),    // 4: grpc.TestVinVcCreationRequest
	(*TestVinVcCreationResponse)(nil),   // 5: grpc.TestVinVcCreationResponse
	(*ManualVinVcCreationRequest)(nil),  // 6: grpc.ManualVinVcCreationRequest
	(*ManualVinVcCreationResponse)(nil), // 7: grpc.ManualVinVcCreationResponse
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_pkg_grpc_atttestation_api_proto_depIdxs = []int32{
	8, // 0: grpc.EnsureVinVcRequest.before:type_name -> google.protobuf.Timestamp
	0, // 1: grpc.AttestationService.EnsureVinVc:input_type -> grpc.EnsureVinVcRequest
	2, // 2: grpc.AttestationService.GetVinVcLatest:input_type -> grpc.GetLatestVinVcRequest
	4, // 3: grpc.AttestationService.TestVinVcCreation:input_type -> grpc.TestVinVcCreationRequest
	6, // 4: grpc.AttestationService.ManualVinVcCreation:input_type -> grpc.ManualVinVcCreationRequest
	1, // 5: grpc.AttestationService.EnsureVinVc:output_type -> grpc.EnsureVinVcResponse
	3, // 6: grpc.AttestationService.GetVinVcLatest:output_type -> grpc.GetLatestVinVcResponse
	5, // 7: grpc.AttestationService.TestVinVcCreation:output_type -> grpc.TestVinVcCreationResponse
	7, // 8: grpc.AttestationService.ManualVinVcCreation:output_type -> grpc.ManualVinVcCreationResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_grpc_atttestation_api_proto_init() }
func file_pkg_grpc_atttestation_api_proto_init() {
	if File_pkg_grpc_atttestation_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_atttestation_api_proto_rawDesc), len(file_pkg_grpc_atttestation_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_atttestation_api_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_atttestation_api_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_atttestation_api_proto_msgTypes,
	}.Build()
	File_pkg_grpc_atttestation_api_proto = out.File
	file_pkg_grpc_atttestation_api_proto_goTypes = nil
	file_pkg_grpc_atttestation_api_proto_depIdxs = nil
}
