definitions:
  internal_controllers_httphandlers.CreateOdometerStatementVCRequest:
    properties:
      timestamp:
        description: Optional timestamp
        example: "2021-01-01T00:00:00Z"
        type: string
    type: object
  internal_controllers_httphandlers.CreateVehicleHealthVCRequest:
    properties:
      endTime:
        example: "2021-01-15T00:00:00Z"
        type: string
      startTime:
        example: "2021-01-01T00:00:00Z"
        type: string
    required:
    - endTime
    - startTime
    type: object
  internal_controllers_httphandlers.CreateVehiclePositionVCRequest:
    properties:
      timestamp:
        example: "2021-01-01T00:00:00Z"
        type: string
    required:
    - timestamp
    type: object
  internal_controllers_httphandlers.getVCResponse:
    properties:
      message:
        type: string
      vcQuery:
        type: string
      vcUrl:
        type: string
    type: object
  internal_controllers_httphandlers.successResponse:
    type: object
info:
  contact: {}
  title: DIMO Attestation API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /v2/attestation/odometer-statement/{tokenId}:
    post:
      consumes:
      - application/json
      description: Generate a new Odometer Statement attestation for a given token
        Id. If timestamp is not provided, uses the latest odometer reading.
      parameters:
      - description: token Id of the vehicle NFT
        in: path
        name: tokenId
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        schema:
          $ref: '#/definitions/internal_controllers_httphandlers.CreateOdometerStatementVCRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers_httphandlers.successResponse'
      security:
      - BearerAuth: []
      summary: Create Odometer Statement Attestation
      tags:
      - OdometerStatementVC
  /v2/attestation/vehicle-health/{tokenId}:
    post:
      consumes:
      - application/json
      description: Generate a new Vehicle Health attestation for a given token Id
        and time range. The time range cannot exceed 30 days.
      parameters:
      - description: token Id of the vehicle NFT
        in: path
        name: tokenId
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_controllers_httphandlers.CreateVehicleHealthVCRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers_httphandlers.successResponse'
      security:
      - BearerAuth: []
      summary: Create Vehicle Health Attestation
      tags:
      - VehicleHealthVC
  /v2/attestation/vehicle-position/{tokenId}:
    post:
      consumes:
      - application/json
      description: Generate a new Vehicle Position attestation for a given token Id
        and timestamp.
      parameters:
      - description: token Id of the vehicle NFT
        in: path
        name: tokenId
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_controllers_httphandlers.CreateVehiclePositionVCRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers_httphandlers.successResponse'
      security:
      - BearerAuth: []
      summary: Create Vehicle Position Attestation
      tags:
      - VehiclePositionVC
  /v2/attestation/vin/{tokenId}:
    post:
      consumes:
      - application/json
      description: Generate a new VIN attestation for a given token Id of a vehicle
        NFT.
      parameters:
      - description: token Id of the vehicle NFT
        in: path
        name: tokenId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers_httphandlers.getVCResponse'
      security:
      - BearerAuth: []
      summary: Create VIN Attestation
      tags:
      - VINVC
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
