definitions:
  internal_controllers_httphandlers.getVCResponse:
    properties:
      message:
        type: string
      vcQuery:
        type: string
      vcUrl:
        type: string
    type: object
info:
  contact: {}
  title: DIMO Attestation API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /v2/attestation/vin/{tokenId}:
    post:
      consumes:
      - application/json
      description: Generate a new VIN attestation for a given token Id of a vehicle
        NFT.
      parameters:
      - description: token Id of the vehicle NFT
        in: path
        name: tokenId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers_httphandlers.getVCResponse'
      security:
      - BearerAuth: []
      summary: Create VIN Attestation
      tags:
      - VINVC
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
